# Generated by Django 3.0.4 on 2022-12-21 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sns', '0002_friend_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='User',
            new_name='user',
        ),
    ]
